COVID19Tracking/covid-public-api-build

config.js
config/sources/status.js
jest.config.js
src/__tests__/sources/status.js
src/output/files.js
src/sources/index.js
src/sources/status.js

Fixes #1 
Adds a new endpoint with
- Build time
- Production mode
- Build number

chore: Added build status

---

jest.config.js
src/__tests__/output/files.js
src/__tests__/sources/us.js
src/sources/us.js
src/write-file.js

- Remove some files from code coverage
- Added test for US daily files
- Added test for file output

chore(test): Coverage on file and us sources

---

.github/workflows/build.yml
package-lock.json
package.json
post-build/utilities/check-file.js
post-build/v1/index.js
post-build/v1/press.js
post-build/v1/states/all-states.js
post-build/v1/states/current.js
post-build/v1/states/daily.js
post-build/v1/states/info.js
post-build/v1/states/screenshots.js
post-build/v1/us/all-days.js
post-build/v1/us/current.js
post-build/v1/us/daily.js
post-build/v1/volunteers.js
src/sources/us.js

chore: Add post-build test

---

.github/workflows/build.yml

Build assets

---

.github/workflows/build.yml
config/sources/states.js
config/sources/us.js

- Strip git directory from uploaded assets
- Added missing score fields to states

Remove git from assets, fix missing score fields

---

config/sources/us.js

Prevents git history from being wiped in US records.

chore: Change lastModified to date of US records

---

src/sources/screenshots.js

fix: Set time on screenshots to UTC

---

src/sources/screenshots.js

Fixes screenshot paths by adding state to path.

chore: Set  screenshot paths

---

config/sources/race-combined.js
config/sources/race-homepage.js
config/sources/race-separate.js

Change the sheet IDs for the race data

chore: Use new racial data tracker data

---

config/sources/states-info.js

Added tertiary screenshot to states info.

chore: Add tertiary screenshot

---

config/sources/screenshots.js
src/__mocks__/sources/screenshots/sample.json
src/__tests__/sources/screenshots.js
src/sources/screenshots.js

Add a `tertiary` field for screenshots

chore: Mapped tertiary field for screenshots

---

.github/workflows/staging.yml

Adds a separate workflow for checking out a staging branch

chore: Allow build dispatch for staging

---

config/sources/screenshots.js
src/output/files.js
src/sources/screenshots.js

- Adds a screenshot file per-state

feat: Add per-state screenshot files

---

config/sources/race-homepage.js
src/__tests__/sources/race-homepage.js

Added missing `asianMortalityRate` field to CRDT homepage.

chore: Added missing asianMortalityRate

---

config/sources/screenshots.js

Fixes the case in the individual state screenshot category

chore: Fix case in screenshot category

---

.github/workflows/build.yml
.github/workflows/volunteers.yml
config.js
index.js
package-lock.json
package.json
src/run/bigquery.js
src/sources/index.js

- Makes volunteers a separate process so we can run data updates faster
- Adds support for fetching all tables or views from a specific BigQuery dataset to a directory
Scheduled merge on July 15

chore: Add volunteer build step, bigquery views fetcher

---

config/sources/states.js
post-build/compare/state-info.js
post-build/compare/states/current.js
post-build/compare/states/daily.js
post-build/compare/us/current.js
post-build/compare/us/daily.js

Change RI to also use total test encounters

chore: Add RI for total test encounters

---

post-build/v1/press.js

chore(test): Remove press post-build test

---

config/sources/us.js

Maps the US total test results to a sheet column

Map US total test results to column name

---

.github/workflows/clean_assets.yml
config/sources/states-info.js
config/sources/states.js

Just use the new Total Test Results field as a data source for TTR in states daily

feat: Use total test results as sole source of TTR

---

config/sources/states.js

Marks totalTestResultsSource in states as deprecated.

chore: Deprecate totalTestResultsSource

---

config/sources/states.js

chore: Add probable cases to state definition

---

config/sources/states-info.js
src/__mocks__/sources/states-info/info.json
src/__tests__/sources/states-info.js
src/sources/states-info.js

Changes the states info endpoint to use the internal API

chore: Update states info to use internal API

---

config/sources/states.js

chore: reorder probable cases to original position

---

.github/workflows/build.yml

Removes cron for the main build workflow

chore: Remove cron

---

config/sources/states.js

chore: Add hospitalizedDischarged

---

src/run/v2/index.js

Removes `beta` label from API v2

chore: Change to v2
